### ISSUE TITLE
@conda-forge-admin, please add user @diogomart

### ISSUE THREAD

**Issue by diogomart** [conda-forge/meeko-feedstock#2]
### Additional comment:

Hi Hadrien,

Thanks a lot for putting meeko on conda-forge! I'm one of the developers of meeko. I'll create another issue to add @nbruciaferri who is also a developer of meeko.

**Comment by hadim** [comment]
See https://github.com/conda-forge/meeko-feedstock/commit/20c2aa8c9220148a3a199cccfef9ceafb4b19c83 for @ diogomart

(you can close here)
